apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-rest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: node-rest
    spec:
      containers:
        - name: node-rest-container
          image: ershangpt/nodejs-express-api-v11
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 500m
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: db-credentials
